[package]
name = "aoc"
version = "0.2.0"
authors = ["ncoif <nicolas@ncoif.net>"]
edition = "2018"

[dependencies]
lazy_static = "1.2"
regex = "1.1"
pathfinding = "1.1"
itertools = "0.8"
regex-syntax = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "all"
harness = false
