[package]
name = "aoc"
version = "0.1.0"
authors = ["ncoif <nicolas@ncoif.net>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
regex = "1.1.0"
pathfinding = "1.1.10"
itertools = "0.8.0"
regex-syntax = "0.6.4"
